### ISSUE TITLE
Support mapping multiple aliases

### ISSUE THREAD

**Issue by kominoshja** [philnash/jekyll-mastodon_webfinger#2]
I know it's a current limitation, but I'd be interested in adding functionality to add more than just a catch-all address, allowing something like:
```yml
mastodon:
 - alias: philnash # resolves philnash@philna.sh to philnash@mastodon.social
   username: philnash
   instance: mastodon.social
 - alias: philnash # resolves team@philna.sh to philnash_team@fosstodon.org
   username: philnash_team
   instance: fosstodon.org
```

Looking forward to comments & feedback
